version: "3"

services:

  web:
    build: main
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - database

  ##############
  # PostgreSQL #
  ##############

  database:
    build: docker/database/
    ports:
      - 5632:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

