package com.hardware.persistence.impl.converters;

import com.hardware.commons.Converter;
import com.hardware.domain.catalog.Device;
import com.hardware.persistence.impl.entities.AutoGeneratedDeviceEntity;
import org.springframework.stereotype.Component;

@Component
public class AutoGeneratedDeviceToEntityConverter implements Converter<Device, AutoGeneratedDeviceEntity> {

    @Override
    public AutoGeneratedDeviceEntity convert(Device source) {

        final AutoGeneratedDeviceEntity deviceEntity = new AutoGeneratedDeviceEntity();
        deviceEntity.setName(source.getName());
        deviceEntity.setBrand(source.getBrand());
        deviceEntity.setCreationTime(source.getCreationTime());
        return deviceEntity;
    }
}
