package com.hardware.persistence.impl.repositories;

import com.hardware.persistence.impl.entities.AutoGeneratedDeviceEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface AutoGeneratedDeviceRepository extends JpaRepository<AutoGeneratedDeviceEntity, Long> {

}
